services:
    redis:
        image: redis:latest
        container_name: ${REDIS_NAME}
        ports:
            - "${REDIS_PORT}:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD:-mysecretpassword}
        command:
            [
                "redis-server",
                "--requirepass",
                "${REDIS_PASSWORD:-mysecretpassword}",
            ]
        volumes:
            - redis-data:/data
        restart: unless-stopped
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        container_name: ${POSTGRE_NAME}
        environment:
            - POSTGRES_USER=${POSTGRE_USER}
            - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
            - POSTGRES_PORT=${POSTGRE_PORT}
            - POSTGRES_HOST=${POSTGRE_HOST}
            - POSTGRES_DB=${POSTGRE_NAME}
        ports:
            - "${POSTGRE_PORT}:5432"

volumes:
    redis-data:
